Fix the missing "type_ignores" exception for Python scripts
Including a PyGMT script gives the following exception:
```
Exception occurred:
  File "/XXX/sphinx_gmt/sphinx_gmt/gmtplot.py", line 239, in eval_python
    exec(compile(ast.Module([node]), filename=filename, mode="exec"))
TypeError: required field "type_ignores" missing from Module
```